# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

commands:
  pnpm-install:
    steps:
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable --install-directory /home/circleci/bin
            corepack prepare pnpm@latest --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install Dependencies
          command: pnpm install --frozen-lockfile
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store

jobs:
  test-run:
    docker:
      - image: cimg/node:23.1.0
    steps:
      - checkout
      - pnpm-install
      - run:
          name: "run index"
          command: |
            export HOGE=$MY_HOGE
            pnpm dev

workflows:
  test-workflow:
    jobs:
      - test-run
